name: Production workflow

on:
  push:
    branches:
      - master
  repository_dispatch:
    types:
      - Webook deploy
  # schedule:
  #   - cron: "0 */2 * * *" # every two hours
  #   - cron: "0 0 * * *" # every 24 hours at midnight

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        id: yarn-cache
        with:
          path: |
            ~/.npm
            node_modules
            */*/node_modules
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-v2-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-v2-

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          npm i -g yarn@1.22.4
          yarn
      - name: Build and Deploy
        run: |
          yarn bootstrap
          yarn build
          yarn deploy:production
        env:
          NODE_ENV: production
          SHOPIFY_STORE_NAME: ${{ secrets.SHOPIFY_STORE_NAME }}
          SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}
          SHOPIFY_THEME_ID: ${{ secrets.SHOPIFY_THEME_ID }}
          SHOPIFY_APP_PASSWORD: ${{ secrets.SHOPIFY_APP_PASSWORD }}
          SANITY_READ_TOKEN: ${{ secrets.SANITY_READ_TOKEN }}
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
          SANITY_PROJECT_ID: ${{ secrets.SANITY_PROJECT_ID }}
          SANITY_DATASET: ${{ secrets.SANITY_DATASET }}
          NETLIFY_API_ID: ${{ secrets.NETLIFY_API_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}